#!/usr/bin/env python3
import argparse
import os
import subprocess
from typing import Optional

import pyperclip


AWS_PROFILE = os.getenv('AWS_PROFILE')


def cp_files(from_loc: str, to_loc: str, dryrun: bool, single_file: bool, run: bool = True) -> Optional[str]:
    flags = '--acl bucket-owner-full-control'  # always want this

    if AWS_PROFILE:  # want this if it is set as an env var
        flags += f' --profile {AWS_PROFILE}'
    if dryrun:
        flags += ' --dryrun'
    if not single_file:  # assume recursive unless told otherwise
        flags += ' --recursive'

    cmd = f'aws s3 cp {from_loc} {to_loc} {flags}'

    if run:
        subprocess.run(cmd, shell=True)
    else:
        return cmd


if __name__ == '__main__':
    parser = argparse.ArgumentParser(prog='awscp', description='Copy S3 files with acl, profile, and recursive flags added automatically')
    parser.add_argument('from_loc', help='S3 path to copy from')
    parser.add_argument('to_loc', help='S3 path to copy to')
    parser.add_argument('--dryrun', help='dryrun the S3 copy', action='store_true')
    parser.add_argument('--single_file', help='Copy a single file, otherwise assumes recursive copy', action='store_true')
    parser.add_argument('--clipboard', help='Copy command to clipboard instead of running', action='store_true')
    args = parser.parse_args()

    if args.clipboard:  # helpful if you want to Slack the command to someone
        pyperclip.copy(cp_files(args.from_loc, args.to_loc, args.dryrun, args.single_file, run=False))
    else:
        cp_files(args.from_loc, args.to_loc, args.dryrun, args.single_file)
